Push image: publish to offical paketo and cf dockerhub repo
paketo-buildpacks/tiny-builder pull request #14
Opened 2020-11-10 20:16 UTC by arjun024

Also use pack v0.14.2
Resolves #2

@paketo-buildpacks/builders-maintainers Could you please review it, and stop short of merging it?

If this looks good to you, I want to get @paketo-buildpacks/core-dependencies to stop the tiny builder jobs in Concourse
before merging this to main.

2020-11-10 22:15 UTC, fg-j requested changes

2020-11-10 22:15 UTC, fg-j commented on .github/workflows/create-release.yml
> +        id=$(docker create buildpacksio/pack:0.14.2)
thanks for doing this 👍

2020-11-10 22:15 UTC, fg-j commented on .github/workflows/push-image.yml
> +        PAKETO_BUILDPACKS_DOCKERHUB_USER: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USER }}
```suggestion
        PAKETO_BUILDPACKS_DOCKERHUB_USER: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
```

2020-11-10 22:15 UTC, fg-j commented on .github/workflows/push-image.yml
> +        PAKETO_BUILDPACKS_DOCKERHUB_USER: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USER }}
(based on what the org-level secret is named)

2020-11-13 15:41 UTC, fg-j approved these changes
Over to you for merge @dumez-k, or let me know when you're ready @martyspiewak.

2020-11-13 15:51 UTC, merged

2020-11-13 16:19 UTC, arjun024 commented
@paketo-buildpacks/core-dependencies Just want to confirm you have stopped the tiny builder jobs in Concourse

2020-11-13 18:44 UTC, martyspiewak commented
@arjun024 Yes we have